name: Publish Page 1

on:
    push: 
        branches: main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write
  
jobs:
    package:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                mkdir dist
                cp -R folder_1 dist
            - uses: actions/upload-pages-artifact@v3
              with:
                name: page-1
                path: dist

    publish:
        runs-on: ubuntu-latest
        needs: package
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              with:
                artifact_name: page-1
